version: 0.0
os: linux
files:
  - source: demo-0.0.1-SNAPSHOT.jar
    destination: .
  - source: start.sh
    destination: .
  - source: stop.sh
    destination: .
hooks:
  ApplicationStop:
    - location: stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      runas: ec2-user