version: 0.0
os: linux
files:
  - source: demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/demo-0.0.1-SNAPSHOT.jar
  - source: start.sh
    destination: /home/ec2-user/start.sh
hooks:
  ApplicationStart:
    - location: start.sh
      runas: ec2-user