version: 0.0
os: linux
files:
  - source: demo-0.0.1-SNAPSHOT.jar
    destination: demo-0.0.1-SNAPSHOT.jar
  - source: start.sh
    destination: start.sh
hooks:
  ApplicationStart:
    - location: start.sh