version: 0.0
os: linux
files:
  - source: demo/demo-0.0.1-SNAPSHOT.jar
    destination: demo-0.0.1-SNAPSHOT.jar
  - source: demo/start.sh
    destination: start.sh
hooks:
  ApplicationStart:
    - location: ./start.sh