name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Build 
      run: ./gradlew build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 
    
    - name: Push
      run: |
        mv build/libs/demo-0.0.1-SNAPSHOT.jar codedeploy/
        aws deploy push --application-name demo --s3-location s3://demo-123634/demo2.zip --ignore-hidden-files --source codedeploy
        aws deploy create-deployment --application-name demo --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name demo-deployment-group --s3-location bucket=demo-123634,bundleType=zip,key=demo2.zip
