name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Jib 
      run: ./gradlew jibDockerBuild

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1 
    
    - name: Push
      run: |
        docker save demo:0.0.1-SNAPSHOT | gzip > demo.tar.gz
        aws deploy push --application-name demo --s3-location s3://demo-123634/demo.tar.gz --ignore-hidden-files

