name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: demo
        path: build/libs/demo-0.0.1-SNAPSHOT.jar
